### ISSUE TITLE
TOTP setup warning although not enabled

### ISSUE THREAD

**Issue by ThomasLeister** [WordPress/two-factor#101]
Hi,

I'm using version 0.1-dev-2015-12-10 of the plugin with only U2F and backup codes being enabled. Whenever I try to save the settings, there is a warning at the top of the page saying: _"Two Factor Authentication not activated, you must specify authcode to ensure it is properly set up. Please re-scan the QR code and enter the code provided by your application."_

I do not have the Google Authenticator method enabled, so I guess this is a bug? Authentication via U2F is working fine.

**Comment by lmartins** [comment]
Was about to report the same problem, happening on two different sites were I just installed the plugin.

**Comment by shield-9** [comment]
Related #77
