### ISSUE TITLE
Does it work for websites that have wp-admin restricted by IP?

### ISSUE THREAD

**Issue by Onyx808** [WordPress/two-factor#180]
I been trying to use google two factor option in a website which wp-admin is restricted by IP.
and I keep getting:
```
Two Factor Authentication not activated, the authentication code you entered was not valid. Please re-scan the QR code and enter the code provided by your application.
```
My guess that this is due to the fact the wp-admin is restricted.

If so, is there a way to get it to work?

Thank you!

**Comment by ragnarkarlsson** [comment]
Restriction by IP shouldn't matter, the Google authenticator app is a TOTP which has no concept of ip address. I've seen this behaviour before when the server & your device's clock are > 1 minute difference in clock (as TOTP use the minute normally). Check that your server's date/time is accurate, eg enable NTP and I suspect you'll find it works perfectly.
