### ISSUE TITLE
Feature: Setting to Force 2F via email for administrators 

### ISSUE THREAD

**Issue by holzhannes** [WordPress/two-factor#185]
It would be nice to have a setting to force the 2F Authentication via email for all users with role Administrator. Therefore in a Multisite (Network) installation there should be a settings page for each site and one for the hole network. If force two factor via email is enabled for the hole network the setting should not be changeable by a single site admin.

**Comment by kasparsd** [comment]
Related #239.

**Comment by iandunn** [comment]
It seems like this is covered by #255 / #239, so I'll go ahead and close it, but let me know if there's anything distinct that I missed.
