### ISSUE TITLE
Email backup codes should have an expiry

### ISSUE THREAD

**Issue by dd32** [WordPress/two-factor#220]
Currently Email Backup Codes are valid until they're used  - even if the user logs in using another backup method.

Ideally even the Email Backup Codes should have an expiry. At the minimum an expiry of a Day would be good here, although more practically an Hour would make sense to me.

**Comment by kasparsd** [comment]
This was also requested on WP.org forums recently https://wordpress.org/support/topic/set-period-of-validity-of-email-codes/

**Comment by NiklasBr** [comment]
> Ideally even the Email Backup Codes should have an expiry. At the minimum an expiry of a Day would be good here, although more practically an Hour would make sense to me.

[OWASP recommends a time-frame around 20 minutes](/OWASP/CheatSheetSeries/blob/master/cheatsheets/Forgot_Password_Cheat_Sheet.md), which is shorter than I expected.
