### ISSUE TITLE
UX - Ability to de-select 2FA Methods

### ISSUE THREAD

**Issue by mdbitz** [WordPress/two-factor#225]
The current UI uses radio buttons for selecting the 2FA methods. After a user selects a method it is not possible to de-select due to the radio button implementation.

**Comment by kasparsd** [comment]
@mdbitz Are you referring to the primary method selector?

![primary-method](https://user-images.githubusercontent.com/169055/47000098-32758c80-d130-11e8-97c1-1a0b326f0720.png)

We need to enforce a single selection there. It can also stay selected even when none of the 2F methods are enabled. Maybe we could unset the primary radio button when all methods have been disabled?

**Comment by jeffpaul** [comment]
This does not appear to be a bug or enhancement and instead a misunderstanding on the enabled/checkboxes and primary/radiobuttons.
