### ISSUE TITLE
Allow admin to disable Time Based One-Time Password on user accounts

### ISSUE THREAD

**Issue by mdbitz** [WordPress/two-factor#226]
In the plugin you can programmatically disable providers using the filter `two_factor_providers ` 
https://github.com/georgestephanis/two-factor/blob/fced6f579161631791c525976a1dbb6211bef35c/class.two-factor-core.php#L85

I'd like to request the ability for Site Admins to disable providers per user. For example the ability to disable the "Time Based One-Time Password" for specific user accounts.

**Comment by iandunn** [comment]
It seems like the `two_factor_enabled_providers_for_user` filter would work for this. It was added in #344

I'll go ahead and close this, but we can always reopen it if there's that PR didn't address.

**Comment by ocean90** [comment]
Created a follow-up since `two_factor_enabled_providers_for_user` isn't useful for this:  https://github.com/WordPress/two-factor/issues/647
