### ISSUE TITLE
Fido U2F table displays even when user has not selected U2F method

### ISSUE THREAD

**Issue by mikeselander** [WordPress/two-factor#243]
If available as an option, the U2F keys table shows underneath the settings screen, even if a user hasn't selected this option yet which makes the interface more confusing. 

My expectation is that the keys table would not display unless a user has chosen this method.

**Comment by My1** [comment]
I'd rather say if not chosen AND no keys as you I am not sure whether disabling also deletes all the associated data

**Comment by iandunn** [comment]
U2F is deprecated and no longer works in Chrome, so the provider is being removed in #439 . Given that, there's probably no reason to keep this open anymore.

A WebAuthn provider is being added in #427 , which currently uses a different table for listing keys.
