### ISSUE TITLE
Point the GitHub project URL to the WP.org plugin page

### ISSUE THREAD

**Issue by kasparsd** [WordPress/two-factor#282]
It would be helpful to change the project URL on GitHub to the [plugin page on WP.org](https://wordpress.org/plugins/two-factor/).

![repo-link](https://user-images.githubusercontent.com/169055/56486426-37046e80-64e0-11e9-8e29-eebe7261fd70.png)

@georgestephanis What do you think?

**Comment by WarenGonzaga** [comment]
I guess this is already done?

**Comment by kasparsd** [comment]
This is now fixed!
