### ISSUE TITLE
Conflict with All-in-one security multisite

### ISSUE THREAD

**Issue by AlanJIsaacson** [WordPress/two-factor#297]
We have installed and are very happy with the plugin, but have found that its login action priority conflicts with the Wordpress All-In-One security plugin as they both have a priority of 10.  

This means we get stuck in an infinite loop of trying to login. 

Is it possible to update the line 
add_action( 'wp_login', array( __CLASS__, 'wp_login' ), 10, 2 );
to be 
add_action( 'wp_login', array( __CLASS__, 'wp_login' ), 15, 2 );

Further details https://wordpress.org/support/topic/unable-to-access-console-when-session-expired/

Many thanks in advance

Alan

**Comment by kasparsd** [comment]
Thanks for the suggestion @AlanJIsaacson!

I think we could increase the priority of the `wp_login` hook since we are actually stopping all further execution during the same default priority 10 and some hooks might not even fire. There should be no harm in bumping it to a larger value.

**Comment by kasparsd** [comment]
Closing as duplicate of #592 since that better describes the cause and the race condition.
