### ISSUE TITLE
Undefined index: hook_suffix

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/two-factor#298]
Version 0.4.7

when registering a yubi key in profile I get: 

```
PHP Error: Undefined index: hook_suffix
\wp-admin\includes\class-wp-screen.php on line 229
Error URL: https://myurl.com/wp-admin/admin-ajax.php
Trace:
#1 \wp-admin\includes\template.php(1988): WP_Screen::get(NULL)
#2 \wp-admin\includes\class-wp-list-table.php(143): convert_to_screen(NULL)
#3 \wp-content\plugins\two-factor\providers\class.two-factor-fido-u2f-admin.php(313): WP_List_Table->__construct()
#4 \wp-includes\plugin.php(463): Two_Factor_FIDO_U2F_Admin::wp_ajax_inline_save()
#5 \wp-admin\admin-ajax.php(99): do_action(wp_ajax_inline-...)
```

**Comment by kasparsd** [comment]
Thanks for reporting the issue @kkmuffme!

Looks like it is happening here:

https://github.com/georgestephanis/two-factor/blob/ab8d6510a17606b200d1e44a603c13b5014bac52/providers/class.two-factor-fido-u2f-admin.php#L313

Is that the first time you're registering the key? Are there any other keys current associated with the account?

**Comment by kkmuffme** [comment]
No the key was registered before. But I deleted the key (by clicking on "Delete")
Then later again registered the key again.

**Comment by kkmuffme** [comment]
Any plans to fix this?

**Comment by iandunn** [comment]
U2F is deprecated and no longer works in Chrome, so the provider is being removed in #439 . Given that, there's probably no reason to keep this open anymore.
