### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by jranma** [WordPress/two-factor#303]
Using Wordpress 5.2.3 FR
Plugin is not working anymore. I get a 403 error after taping my yubikey.

**Comment by pwaring** [comment]
What version of the plugin are you using? I have WordPress 5.2.3 and Two Factor 0.4.7 and my Yubikey works fine.

**Comment by jranma** [comment]
same here, version 0.4.7
It used to work fine until very recently. Recently I added a directory on my wp structure, but it's probably unrelated... 

When I tap my key, I get redirected to https://HIDDEN/wp-login.php?action=validate_2fa
which displays: 

Accès interdit!
Vous n'avez pas le droit d'accéder à l'objet demandé. Soit celui-ci est protégé, soit il ne peut être lu par le serveur.

Si vous pensez qu'il s'agit d'une erreur du serveur, veuillez contacter le webmestre.

Error 403

**Comment by pwaring** [comment]
If you're getting a 403 error, that's usually coming from the web server and not the plugin or WordPress.

> I added a directory on my wp structure, but it's probably unrelated...

Can you undo that change, to make sure that it is definitely unrelated?

**Comment by jranma** [comment]
it's coming from the webserver. 
logfile doesnt help much, just found another code: 
 [01/Oct/2019:12:12:49 +0200] "POST /wp-login.php?action=validate_2fa HTTP/1.1" 403 1051

1051 = "No authorization to access client"

**Comment by jranma** [comment]
I deleted the folder: it's unrelated.

**Comment by mauwiks** [comment]
It doesn't work anymore for email authentication as well

**Comment by kasparsd** [comment]
@jranma Could you please confirm if you deleted the `two-factor` plugin directory and it didn't make the problem go away?

**Comment by teunrutten** [comment]
This is still an active issue. When using Two Factor, we get an 502 Bad Gateway error when trying to login.

**Comment by kasparsd** [comment]
@teunrutten I'm unable to replicate the issue on any of my sites. Could you please share the relevant information from the PHP error logs?
