### ISSUE TITLE
Bug: This plugin does not support the plugin "All In One WP Security"

### ISSUE THREAD

**Issue by Creeper19472** [WordPress/two-factor#331]
"All in One Security" is a security protection all-in-one plugin. After enabling the "Two-factor" plugin, it failed to log in (after entering the verification code, "Your session has expired in XX minutes" and asked to log in again, repeating this cycle)
Please fix it!

**Comment by kasparsd** [comment]
Hi! Could you please confirm the version of the Two Factor plugin you are using? Did this start happening after the 0.5.1 release or before it too?

Please test with version 0.5.0 to confirm.

**Comment by Creeper19472** [comment]
Both versions have this problem. After updating the 0.5.1 version, I think this problem has been fixed, but I was forced to log out when I launched the plugin
In addition, I opened CDN. Is it related to this? Thank you.

**Comment by kasparsd** [comment]
I’m sorry — I don’t fully understand the status of this issue from that description. Is it working with the latest version of the two-factor plugin?

Closing until we know the exact steps to reproduce the issue and the potential reason for the problem as it relates to the two factor codebase.
