### ISSUE TITLE
Support WooCommerce

### ISSUE THREAD

**Issue by DestructiveBurn** [WordPress/two-factor#334]
Can you please add this to WooCommerce Login Page (My Account) for Customers.  It's really needed.   The main profile page is disabled so it makes this 2FA completely useless for everyone else.

It would be greatly appreciated, thanks.

**Comment by kasparsd** [comment]
Are you referring to the two-factor settings in the user profile page? I've created #335 as a generic issue for allow the two-factor user settings to be portable to various screens.

There is also #249 for adding general plugin settings where certain two-factor providers could be enabled for all users by default, for example.

**Comment by DestructiveBurn** [comment]
Well, you just closed this quick.  
Looks like I'll be looking for a plugin that supports Woocommerce.  This one does not.

**Comment by kasparsd** [comment]
Sorry for the confusion @DestructiveBurn -- I just merged this into a generic issue #335 so that this feature wouldn't be limited to WooCommerce only. 

It looks like there are very few active contributors to this plugin right now so finding an alternative might be a good solution.

**Comment by DestructiveBurn** [comment]
I got you.  Well, I hope you do find some contributors.  It's a great plugin.
