### ISSUE TITLE
Unspecific "Bad U2F request" error when attempting to register U2F devices

### ISSUE THREAD

**Issue by assarbad** [WordPress/two-factor#338]
I have installed the plugin in three different WordPress instances (and unfortunately first in the non-functioning one).

I was already about to file a ticket here, since [this forum post](https://wordpress.org/support/topic/how-to-setup-7/) claimed that there was no additional step required other than installing and activating the plugin. However, I then installed it in my other two WordPress instances and I also saw that it worked fine with TOTP.

So TOTP works on all my sites, but registering U2F keys fails consistently on a site which runs on a `.physio` TLD. Now this being the main difference, i.e. having a modern domain name rather than a traditional one, struck me as a possible cause for the consistent failure.

How can I tickle more information out of the instance running on the `.physio` TLD without outright enabling full-fledged WP debugging?

I have to agree with #197, it would be incredibly helpful to get meaningful error messages rather than a generic one. But perhaps there's a security reason behind it, which I don't see (akin to not telling a user whether a user name exists or not or whether the password was simply entered incorrectly).

I cleared the Browser Console (Firefox on Linux Mint tricia with U2F enabled) and then attempted the registration process. The error appears immediately. No dialog popping up such as on the other WordPress instances.

Thanks,

Oliver

PS: perhaps the documentation could mention using the browser console. Something that I only gleaned from reading #173, but wish had been more obvious. A backlink to the Wiki perhaps?

**Comment by kasparsd** [comment]
> Now this being the main difference, i.e. having a modern domain name rather than a traditional one, struck me as a possible cause for the consistent failure.

@assarbad Were you able to confirm this? The hostname of the site is used for the FIDO U2F `AppID` here:

https://github.com/WordPress/two-factor/blob/2b4ce5cd41a8859f5524f651493151baa61b7683/providers/class.two-factor-fido-u2f.php#L108-L116

and that should work with any string that "looks" like a hostname.

**Comment by My1** [comment]
I kinda doubt that a new domain name would be an overly big issue, I have run on a tech and a dev no issue.

in case you dont mind you could give me a permissionless user (aka subscriber role, which only can manage their own profile) so I could maybe try and look at the requests it's kicking out.

https://wordpress.org/support/article/roles-and-capabilities/

**Comment by kasparsd** [comment]
Thanks for offering your support @My1!

I'm going to close this out until we figure out the actual cause of the problem and if it can be fixed in the plugin. Without access to the particular U2F device it is hard to debug this further.

**Comment by My1** [comment]
well I have quite a few so many of the common ones (like yubikey Solo or Feitian) are things I can test
