### ISSUE TITLE
Pressing Enter when "Time Based One-Time Password" is set up causes it to reset

### ISSUE THREAD

**Issue by dartiss** [WordPress/two-factor#341]
It can be best demonstrated with this GIF...

![blog-2fa-issue-local](https://user-images.githubusercontent.com/14928971/77904271-30e44980-727c-11ea-95c5-bdb51902be06.gif)

Basically, set up your 2FA preference as "Time Based One-Time Password". Then go to any other profile field, update it and then press Enter (i.e. don't use the "Update Profile" button). You'll find that the 2FA setting have no deactivated.

I believe this is because pressing Enter is causing the "Reset Key" button to trigger instead of "Update Profile", due to it being the first form input.

**Comment by kasparsd** [comment]
Thanks for opening this @dartiss! I wonder if #91 is related to this as well.

**Comment by georgestephanis** [comment]
For a bit of added context, the additional code causing that modal is coming from https://github.com/Automattic/vip-go-mu-plugins/blob/master/two-factor.php#L223

**Comment by kasparsd** [comment]
I think @dartiss is spot-on -- the issue is caused by the "Reset Key" button being the first "submit" type button in the form:

https://github.com/WordPress/two-factor/blob/9ca399ad5df9a5dc498e790d7bd820610550ae93/providers/class.two-factor-totp.php#L107

This was introduced in #252.

**Comment by georgestephanis** [comment]
Would we have the same usability without the issue if it was a `<button>` instead of `<input>` or would that cause a11y issues?

**Comment by kasparsd** [comment]
@georgestephanis There shouldn't be an issue with switching to `<input type="button" />` or `<button />` as long as we make it submit the form on click/press which is not the default behaviour for non-submit buttons:

> To make buttons do anything, you have to write JavaScript code to do the work.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button

**Comment by georgestephanis** [comment]
It's always hard to do one form inside another.  *laugh*

**Comment by rahulsprajapati** [comment]
We could use a checkbox or something and rely on to remove/reset config rather then submit button value.

I've found a workaround to add fix: https://gist.github.com/rahulsprajapati/c08182f1fc88596bb3c2206e0eea4a60

If this make sense we could add it in plugin itself.
cc @dartiss

**Comment by dartiss** [comment]
Thanks @rahulsprajapati. How is this solution in terms of accessibility?

**Comment by rahulsprajapati** [comment]
> How is this solution in terms of accessibility?

Yeah it work just fine, check this gif. 

![2fa-fix](https://user-images.githubusercontent.com/10358350/78971055-539e1a00-7b28-11ea-9e7f-c2bdd93d5e5b.gif)
