### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by uvedhe** [WordPress/two-factor#359]
Hi all,

I seem to be unable to login when this plugin is enabled. When I go to the admin login page and fill in username and password, I get directed to the page for the OTP, but when I fill that in I get directed back to the login page with the errors 

`Error: the username field is empty.`
`Error: the password field is empty.`

Logging in with a user that does not have Two-Factor enabled works fine.

Specs:
Wordpress 4.5.1
Two-factor 0.6.0

**Comment by kasparsd** [comment]
@uvedhe Could you please confirm the list of all the other plugins you have installed and the theme? This looks like a potential integration issue with another plugin. Could there be any "security" plugins?

**Comment by uvedhe** [comment]
Yes I'm also running "All In One WP Security" 4.4.3 and "Protect WP-Admin" 3.1

**Comment by kasparsd** [comment]
@uvedhe Could you try disabling both of those plugins for a test? I'm pretty sure one of them is causing a conflict.

**Comment by uvedhe** [comment]
@kasparsd it turns out "Protect WP-Admin" is the culprit, probably because it changes the URL? Is there any interest in finding out how to solve this for Two-Factor, as the two plugins are complementary in their functioning?

**Comment by kasparsd** [comment]
Thanks for sharing your findings @uvedhe! This will be really useful for other users.

Unfortunately, I personally don't have time to investigate this further.
