### ISSUE TITLE
wp_register_script causes a PHP Notice

### ISSUE THREAD

**Issue by anekola** [WordPress/two-factor#361]
I have no idea why I just started getting this, but I just updated this [VIP Go repo](https://github.com/Automattic/vip-go-mu-plugins) in my local environment and I suddenly started getting two PHP notices. Turns out the notice came from these functions:

https://github.com/WordPress/two-factor/blob/529c973deb4677e45cc243b1336dd718aa472611/providers/class.two-factor-fido-u2f.php#L70

`Notice: wp_register_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /srv/www/ona-journalists/public_html/wp-includes/functions.php on line 5167
`

**Comment by PypWalters** [comment]
Seeing the same issue as well.
