### ISSUE TITLE
One-time Password App suggestions

### ISSUE THREAD

**Issue by kasparsd** [WordPress/two-factor#367]
From https://wordpress.org/support/topic/request-clarify-copy-around-tone-time-password-authentication-apps/

> Our client thought Google Authenticator was required for use because of how the description for the time based one-time password option reads [..] Please clarify that Google Authenticator is an example of an app. So something as simple as: Time Based One-Time Password (e.g. Google Authenticator)

**Comment by r-a-y** [comment]
Agreed. Perhaps consider renaming "Time Based One-Time Password (Google Authenticator)" to the more-used "Authenticator App"?

Also "FIDO Universal 2nd Factor (U2F)" should be renamed to "Security Keys".

And the "Name" header in the table should be renamed to "Type"
