### ISSUE TITLE
Solo key firmware v4.0.0 not able to login newly registered key

### ISSUE THREAD

**Issue by corbolais** [WordPress/two-factor#372]
Hi,

I recently filed an [issue with the solo key firmware repo](https://github.com/solokeys/solo/issues/459). I first noticed this using the wordpress plugin Two-Factor. Also, it seemed to work on a test site https://webauthn.org/. Now, after trying one more independent site successfully, it looks more like this Two-Factor plugin has an issue rather than the solo key firmware.

ATM, I'm not in a position to investigate and file a PR but I shall be happy to assist and test any patch related to this issue.

Thank you.

Cheers

**Comment by kasparsd** [comment]
Thanks for reporting the issue @corbolais!

I'm using SOMU (reported as "Solo 3.0.1") with the two-factor plugin and it works great. Was it working before you upgraded the firmware to 4.0.0?

Does it fail at the registration stage or the authentication stage? Have you tried re-adding the key to your user profile in the WP admin?

I just updated my SOMU to firmware 4.0.0 and I'm getting the "ERROR: Invalid verification code." error when trying to authenticate now (which is coming [from here](https://github.com/WordPress/two-factor/blob/e2638ff3f0b5117056333fde006043957a1fc210/class-two-factor-core.php#L860)).

I was able to re-register the key after removing the old key from the WP profile. Could it that updating the firmware also resets the private key?

> Warning: After this update, any existing RK's on your device will likely not work anymore. If you're not sure about what RK/resident-key is, then you probably do not have any and do not need to worry.

https://github.com/solokeys/solo/releases/tag/4.0.0

**Comment by corbolais** [comment]
Hello @kasparsd 

> I'm using SOMU (reported as "Solo 3.0.1") with the two-factor plugin and it works great. Was it working before you upgraded the firmware to 4.0.0?

It was, indeed. See also https://github.com/solokeys/solo/issues/459 .

> 
> Does it fail at the registration stage or the authentication stage? Have you tried re-adding the key to your user profile in the WP admin?

It did not fail at the registration stage (iirc) but consistently fails at the auth stage. 
Yes, I deleted and re-added the key multiple times, to no avail.

> 
> I just updated my SOMU to firmware 4.0.0 and I'm getting the "ERROR: Invalid verification code." error when trying to authenticate now (which is coming [from here](https://github.com/WordPress/two-factor/blob/e2638ff3f0b5117056333fde006043957a1fc210/class-two-factor-core.php#L860)).

Sounds like it. :sarcasm: Congrats, you just rendered your somu useless for WP T-F use. :/sarcasm: ;-)

> 
> I was able to re-register the key after removing the old key from the WP profile. Could it that updating the firmware also resets the private key?
> 
> > Warning: After this update, any existing RK's on your device will likely not work anymore. If you're not sure about what RK/resident-key is, then you probably do not have any and do not need to worry.
> 
> https://github.com/solokeys/solo/releases/tag/4.0.0

This might be an issue. But in my understanding, re-registering the key should solve this issue, shouldn't it?

Anyway, thank you for your feedback.

One thing, though, is puzzling me: why did you close this issue?

**Comment by kasparsd** [comment]
> One thing, though, is puzzling me: why did you close this issue?

@corbolais Sorry for the confusion. To me this appears to be an issue with the SOMU firmware. There haven't been any changes to the U2F library used in this plugin in any of the recent releases, too.

**Comment by corbolais** [comment]
> @corbolais Sorry for the confusion. To me this appears to be an issue with the SOMU firmware. There haven't been any changes to the U2F library used in this plugin in any of the recent releases, too.

But.. I got no SOMU, just some Solo Taps and Solo Hackers. Are you intending SOMU and Solos share firmware?

And why does https://webauthn.org/ work then? And other sites, too? Only WP w/ TF-auth plugin is failing.

**Comment by kasparsd** [comment]
Yes, it is my understanding that they share the same firmware.

**Comment by My1** [comment]
> And why does https://webauthn.org/ work then? And other sites, too? Only WP w/ TF-auth plugin is failing.

because U2F (the JS API) and Webauthn work differently and are based on CTAP1/U2F (the hardware API) and CTAP2/FIDO2 respectively.

This thing uses the classic U2F API which might have some bugs in the solo/somu fw, no idea.

@corbolais 
1) yes solo and somu share fw
also can you try some things on my sandboxes if you have no problem with it?

https://my1.dev/wa/my1.php
https://my1.dev/u2f/my1.php

both use seperate databases for keys and all so they run independently of each other. an "account" is signified by the User ID (webauthn sandbox) and Username (U2F sandbox)

especially if you have multiple, try registering them under the same ID and see whether you get any issues regarding anything.
also I am trying to make it more verbose as time goes on.

**Comment by corbolais** [comment]
@My1 thanks for the feedback. Cannot test them right now, time constraints. But will do in a couple of weeks. (yikes)

Did I mention, yubikey nano 4's do not exhibit this behaviour or any problem at all for that matter?

**Comment by My1** [comment]
you didnt but I wasnt expecting them.

maybe stuff is a ton easier when you have just U2F and not FIDO2 to worry about.
