### ISSUE TITLE
Time Based One-Time Passwords (TOTP) (improves: time tolarance +/- 4 minutes, SHA256, and 8 digits)

### ISSUE THREAD

**Issue by JohnPlanetary** [WordPress/two-factor#375]
In the "Time Based One-Time Passwords (TOTP)" function you could add the option for it to tolerate +/- 4 minutes of difference (accepting those codes). These should stop people being blocked because the server and/ or the client don't have the clock with the exact time.

The algorithm could be a little better: SHA256
And the number of digits to enter could improve from 6 to 8 .

WinAuth (Windows) and FreeOTP (Android) I know they support without problem.

These should make it a little harder to guess in a online attack.

**Comment by My1** [comment]
well winauth and freeotp can but for example authy and google authenticator are relatively limited in what works, especially changing the algo, so not sure on the latter 2 parts.

+-4 minutes, sounds like a lot. current seems 2.

also you can apparently filter this.
https://github.com/WordPress/two-factor/blob/master/providers/class-two-factor-totp.php#L321

algo and digits cannot yet but are built in a way that makes this relatively easy to implement.

**Comment by kasparsd** [comment]
We're currently not passing the `algorithm` and `digits` parameters to the Authenticator app in the QR code so [it defaults to SHA1](https://github.com/google/google-authenticator/blob/b5d6e341d0516d731771f890eba66029c95e52e1/mobile/ios/README#L17) and 6 digits.

https://github.com/WordPress/two-factor/blob/736473edf5ff6d2fed18ba2406c772f30950343c/providers/class-two-factor-totp.php#L428-L432

The current setup also doesn't store the parameters used with each secret so this would have to be implemented before we can changes these parameters.
