### ISSUE TITLE
Error 502 on login

### ISSUE THREAD

**Issue by 7php** [WordPress/two-factor#378]
Hello, I have been using this plugin since the start of the year, and did not have any issue until today.

CONTEXT:
When I login, it normally does a redirects to ask me to very either TOTP or key.
But now when instead I get a 502 Error.

WHEN THIS HAPPENED?
After I upgraded to WordPress 5.4.2

But the weird thing is, I have the same setup on another server and I do not get that issue.

Any hints of how I can debug this further?

(Right now, I am using wp-cli to disable to login and then re-enable)

**Comment by kasparsd** [comment]
@7php Could you please check the server error logs. There should be some indication of what the actual error is.

**Comment by 7php** [comment]
Hi @kasparsd 
I managed to solve it. It was not an issue with `two-factor`.

The server complained about "**_upstream sent too big header while reading response header from upstream_**" when `two-factor` was trying to redirect for the 2-FA auth.

I increase the buffer size and it seems to be OK now. 
I thought I had that covered, seems like on this server I had an old config, which blurred my judgement in ruling out this part.

/c Shoutout to @mattiasgeniar - google sent me over to: https://ma.ttias.be/nginx-proxy-upstream-sent-big-header-reading-response-header-upstream/ which urged me to recheck the buffer size - good stuffs!
