### ISSUE TITLE
Email auth codes copy paste issue

### ISSUE THREAD

**Issue by shay1383** [WordPress/two-factor#379]
When double-clicking an auth code to copy it, it also selects a blank space that the auth submission form detects as an extra digit.
https://prnt.sc/u40blj
https://prnt.sc/u40cqk
It's very minor issue, but also a very annoying one.
I suggest you modify it to ignore spaces, or modify the way the auth code is provided. e.g: https://prnt.sc/u40how
Thank you for the awesome plugin!

**Comment by kasparsd** [comment]
Thank you for the suggestion @shay1383!

I've added some logic that removes the empty spaces around the code before doing the comparison in #382.
