### ISSUE TITLE
TOTP: Add description paragraph when attempting to login

### ISSUE THREAD

**Issue by r-a-y** [WordPress/two-factor#380]
Right now when using TOTP as 2FA, only an "Authentication Code" textbox is shown:

![Screenshot of current TOTP](https://user-images.githubusercontent.com/505921/91108429-9a1f8b80-e667-11ea-88fb-ba53510f76fa.png)

I think a paragraph describing what needs to be done should be added for better UX.

Something as simple as the following would suffice:

`Please enter the code from your device's authenticator app.`

![Screenshot of proposed TOTP](https://user-images.githubusercontent.com/505921/91108453-a60b4d80-e667-11ea-918a-5403baf08dce.png)

If not, can you add a `do_action()` hook directly after this line so we can do our own thing?

https://github.com/WordPress/two-factor/blob/7b8129149874793e25d8c487a980dc4671d9af64/providers/class-two-factor-totp.php#L460

Thanks for considering!

**Comment by kasparsd** [comment]
This is a great suggestion!
