### ISSUE TITLE
Dummy Method

### ISSUE THREAD

**Issue by KodaCHC** [WordPress/two-factor#383]
Hi

Grat Plugin. Thank you. I have two questions.

In one installation I see the dummy method, in another I do not. What does this depend on?

Where do I find the MO files? I'm looking for the de_de, but there is no languages folder in the plugin itself and I can't find them in the wp-content\languages\plugins either.

Edit: Is there a possibility to set that 2FA is mandatory for single groups or for all?

Koda

**Comment by kasparsd** [comment]
> In one installation I see the dummy method, in another I do not. What does this depend on?

The "dummy method" is available only if the `WP_DEBUG` is set to `true`:

https://github.com/WordPress/two-factor/blob/feb4708f5951d917c65c8d8f470a06c0264c238a/class-two-factor-core.php#L175-L181

> Where do I find the MO files?

Translations are handled via the WP.org interface https://translate.wordpress.org/projects/wp-plugins/two-factor/

> Is there a possibility to set that 2FA is mandatory for single groups or for all?

Yes, it is possible using a filter similar to this https://github.com/WordPress/two-factor/issues/307#issuecomment-624843209
