### ISSUE TITLE
Two Factor conflicts with Booked

### ISSUE THREAD

**Issue by shay1383** [WordPress/two-factor#392]
Hello
For some reason whenever I'm activating the Two Factor plugin, the page where I put Booked's shortcode "[booked-profile]" to show profile info & Login/Register forms breaks like that: https://prnt.sc/v40nit (And nothing is clickable). Here's how it looks when Two Factor is disabled: https://prnt.sc/v40mu0
I suspect it's because both plugins interfere with the WordPress login mechanism but it's just a guess ¯\_(ツ)_/¯
Here's booked if needed to recreate the issue: https://gofile.io/d/cMHYCD
Thank you!

**Comment by kasparsd** [comment]
Thanks for reporting the issue @shay1383!

This appears to be caused by a conflict with another plugin so I'll close this for now until we confirm the exact things that would need to be changed in the two-factor plugin to make it work with the Booked plugin.
