### ISSUE TITLE
Hide My WP Ghost Two-Factor issue

### ISSUE THREAD

**Issue by SuperMaximus1984** [WordPress/two-factor#396]
After hiding wp-admin (->changing to a different name)  in Hide My WP Ghost plugin, using Two-Factor plugin makes the user unable to see OTP (using email). It doesn't redirect to a correct path and throws back "502 Bad Gateway".
When "wp-admin" is unchanged, plugin works like a charm.
Please advise how to solve this. Need to hide wp-admin anyway...
Thanks!

**Comment by kasparsd** [comment]
The two-factor hooks into `wp_login` and displays the second factor input form per this logic:

https://github.com/WordPress/two-factor/blob/b1b36ffea88fa44ae456e1803ff35a1c122cfced/class-two-factor-core.php#L70

The `wp-admin` string isn't used outside of file includes (per https://github.com/WordPress/two-factor/search?q=wp-admin) so it shouldn't be used for any of the second factor action URLs. Is "Hide My WP Ghost" renaming the actual `wp-admin` directory on the filesystem? 

Can you please share the exact PHP error message from the server logs when the "502 Bad Gateway" error happens?

This appears to be an integration issue with another plugin so I'll mark it as closed for now until we confirm the exact problem with the two-factor plugin, if any.
