### ISSUE TITLE
SMS 2FA Option

### ISSUE THREAD

**Issue by WarenGonzaga** [WordPress/two-factor#397]
I'm aware with the extension however the project is not maintained and might have issues with the latest versions of WordPress. It would be nice if this feature can be native and as part of this extension. I would prefer Twilio for the gateway (also add more gateway in the future if possible).

What do you think guys?

**Comment by kasparsd** [comment]
Thanks for the suggestion @WarenGonzaga! Since this would always require some kind of third party integration for sending the actual SMS, it is better to leave it to other plugins.

**Comment by jeffpaul** [comment]
@WarenGonzaga if you research SMS options and find that hooks are needed in the 2FA plugin to support an SMS extension then please let us know!

**Comment by iandunn** [comment]
WordPress.com has written an SMS provider if anyone wants to fork it for their own use:

https://github.com/Automattic/vip-go-mu-plugins/blob/bcbea5d94671aedbd8a60959dc780b266bb74237/wpcom-vip-two-factor/sms-provider.php

https://github.com/Automattic/vip-go-mu-plugins/blob/bcbea5d94671aedbd8a60959dc780b266bb74237/lib/sms.php
