### ISSUE TITLE
500 Error When a Previous Code is Used

### ISSUE THREAD

**Issue by alexclst** [WordPress/two-factor#399]
1Password recently had a bug where its browser extension would hand out the wrong code in the sequence for a given TOTP second factor. In this situation this plugin would land the `validate_2fa` step with a **500 Server Error**. While refusing to accept the code that is no longer valid is the appropriate response, it seems like a friendlier thing to do than server error would be to land the user back at the login screen with an error message above the fields explaining what went wrong (similar to what already happens if a code from an entirely different sequence is used). In fact, it took me a while to realize this was a timing issue with 1Password and not a plugin conflict on my new site, since it was a server error versus a friendlier error message within the login page of WP.

I'd suggest changing the behavior of this sort of wrong-code-in-sequence error from causing a **500 Server Error** to being treated like any other WP login error, that shows a friendly message above the login fields.

**Comment by kasparsd** [comment]
@alexclst Can you please confirm the error string was reported in the logs when this happened? There shouldn't be a 500 server error when this happens. Here is the relevant section of the code that checks for the validity of the code:

https://github.com/WordPress/two-factor/blob/f10c28943ec4d71d78e510a6184e19d2d2f5c71a/providers/class-two-factor-totp.php#L290-L299

and it should display the error message per the general logic here:

https://github.com/WordPress/two-factor/blob/b1b36ffea88fa44ae456e1803ff35a1c122cfced/class-two-factor-core.php#L830-L840

It should display the same input form with an error message on top.

**Comment by alexclst** [comment]
I can't really confirm this because it has been long enough that I don't quite remember the exact time nor necessarily still have that log easily accessible.

**Comment by kasparsd** [comment]
Thanks for confirming that @alexclst! I'll close this for now until we can confirm the exact place where the error was happening. Maybe it was an issue with a server setup?
