### ISSUE TITLE
Renaming hardware security key doesn't work 

### ISSUE THREAD

**Issue by CompuRoot** [WordPress/two-factor#408]
|Product|Version|
|---|---|
|Wordpress:| 5.7|
|Two-Factor plugin:| 0.7.0|

---
**Issue:** 
I had multiple different U2F/FIDO/OTP/OpenPGP... devices _(that are marked to distinguish between the same brand)_.
When I added security key to 2FA plugin, I defiantly need to rename  default key name from "`New Security Key`" to a different name that match marks on security keys that been used.

If I click to `rename` and change the name, it do nothing after user profile saved, it still always keep security key name as the default one: `New Security Key`

**Comment by kasparsd** [comment]
Tested this and it appears to be working as expected:

https://user-images.githubusercontent.com/169055/189150073-59f83562-e5f4-468a-8219-85bfc339bc74.mp4

Are there any error logs in the browser console or on the server?
