### ISSUE TITLE
Officially support WP 5.8, TOTP partially broken

### ISSUE THREAD

**Issue by nursoda** [WordPress/two-factor#413]
WP is auto-updated to latest version (5.8 today) (which is a good idea due to security). Yet the plugin states, it's not compatible.

TOTP reports for all user profiles that the Token must be reset. Doing so results in a broken image icon instead of the QR code, and even when manually adding the Token-Key as text, it's not saved. So, I can use Backup, Email and FIDO but not TOTP.

**Comment by kasparsd** [comment]
The plugin is working correctly with WP 5.8 on all of the sites that I manage. Could you please elaborate on the issue?

> TOTP reports for all user profiles that the Token must be reset. 

Can you please share a screenshot of this? I'm not aware of such notices or functionality being part of this plugin.

We can re-open the issue once we have a clear understanding of what is not working as expected.

**Comment by nursoda** [comment]
![CSP](https://user-images.githubusercontent.com/8425483/132222090-c6865bcc-6832-456b-8523-159e3150278a.png)
Does that help?

**Comment by kasparsd** [comment]
This is great, thank you @nursoda!

It appears that the browser is blocking the remote request to the Google API for generating the QR codes. There is an issue for converting this into a local service for generating the QR codes #388.

Is there anything else that isn't working as expected outside of the QR code generation?

**Comment by nursoda** [comment]
No, the Rest works as expected. I'm even able to use the secret as shown to register TOTP using AndOTP.

For data protection reasons I'm glad to hear that you're looking for a local alternative to the Google API.

Yet, I did not change anything to prevent the site from loading external ressources since I edited my profile last time. Will check with web devs. Thanks.

**Comment by kasparsd** [comment]
> Yet, I did not change anything to prevent the site from loading external ressources since I edited my profile last time. Will check with web devs. Thanks.

This probably happened with a browser update as they recently introduced stricter cross-origin policies https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default
