### ISSUE TITLE
Duplicated plugin code on wordpress.org

### ISSUE THREAD

**Issue by dziudek** [WordPress/two-factor#422]
Hi,

It seems that the package with plugin contains duplicated code inside two-factor catalog after unpack.
![screen](https://user-images.githubusercontent.com/22004/137764947-a84b2807-bc98-4b29-90ba-ef03557dbc15.png)

I am not sure but most probably it can lead to the error `The plugin does not have a valid header.` during install:
https://wordpress.org/support/topic/cannot-activate-plugin-69/

**Comment by jeffpaul** [comment]
@kasparsd I'm not seeing this in our Git structure... any idea if that snuck in somehow in the release process?

**Comment by jeffpaul** [comment]
Worth confirming that I also see this in SVN: https://plugins.trac.wordpress.org/browser/two-factor/trunk#two-factor

**Comment by kasparsd** [comment]
I've deleted the second `two-factor` directory from the SVN `trunk` so the ZIP should be fixed soon https://plugins.trac.wordpress.org/changeset/2698474

**Comment by kasparsd** [comment]
I've just done a another `npm run deploy` with the WP core version bump #434 and it doesn't appear to have added the `two-factor` sub-directory so I'm really not sure how it ended up landing there https://plugins.trac.wordpress.org/changeset/2698480

Closing for now.
