### ISSUE TITLE
Use hash_equals for email

### ISSUE THREAD

**Issue by Rahe** [WordPress/two-factor#425]
Hello,

On https://github.com/WordPress/two-factor/blob/cf55e92bef8f44ffeed2d4f144dc177a4cb742ca/providers/class-two-factor-email.php#L190 the hashes are compared with `!==`.
It seems better to compare them with the function `hash_equals` instead.

Nicolas,

**Comment by kasparsd** [comment]
Fixed in #426

**Comment by Timmieke** [comment]
Could it be, that something went wrong in this part. Plugin functions normal, but there are no emails sent anymore.

**Comment by kasparsd** [comment]
@Timmieke I've verified on my personal blog that the 2FA over email works as expected -- I'm able to receive the codes and login using them.

This particular change is for the code comparison logic so it shouldn't impact the delivery of emails or the generation of the tokens.

**Comment by Timmieke** [comment]
Ok, sorry... i will retest it, thanks!
