### ISSUE TITLE
Two Factor no longer accessible in MemberPress

### ISSUE THREAD

**Issue by cafestifflered** [WordPress/two-factor#430]
Hello,

I have installed the latest versions of the Two Factor and MemberPress plugins. At one point in the past, the 2FA tab was available for members to access, but that no longer seems to be the case.

https://docs.memberpress.com/article/337-2-factor-authentication-integration-by-plugin-contributors

I don't know if this is caused by MemberPress or Two Factor, but I'd be grateful for assistance.

**Comment by PluginVulnerabilities** [comment]
That seems like an issue that the developer of MemberPress should resolve with their integration.

**Comment by jeffpaul** [comment]
@cafestifflered seems as though MemberPress has added compatibility in their integration and noted so in their docs such that this can be closed now?
