### ISSUE TITLE
Deleting physical security key fails after renaming

### ISSUE THREAD

**Issue by 68kHeart** [WordPress/two-factor#431]
Hello! I came across the following issue involving an error with the physical security key interface under the Profile page:

**How to Reproduce Issue:**
1. Register new security key
2. Rename the security key
3. Delete the now-renamed security key

**Expected Results**
Page reloads with the security key removed

**Actual Results:**
Page returns an HTTP 400 Bad Request, page content is just `0`, and the security key is still registered

**Environment:**
- WordPress 5.9.1
- PHP 8.1.3
- MySQL 8.0.26
- Two Factor 0.7.1

**Additional Notes:**
This issue does not occur if you rename the security key, refresh the page, and _then_ delete it.

**Comment by iandunn** [comment]
U2F is deprecated and no longer works in Chrome, so the provider is being removed in #439 . Given that, there's probably no reason to keep this open anymore.

A WebAuthn provider is being added in #427 , which currently uses a different table for listing keys. If this bug reappears once that's released, we could reopen it.
