### ISSUE TITLE
Maybe add a filter hook for the TOTP QR code URL

### ISSUE THREAD

**Issue by roytanck** [WordPress/two-factor#443]
I'm evaluating this plugin for use in my client's projects. Unfortunately, generating QR codes using googleapis is a hard no-go for them. Having a filter hook in `get_google_qr_code` would allow me to use a local QR generator instead.

Adding a filter hook in that function should be pretty straightforward, and I don't think it would introduce any other issues?

**Comment by roytanck** [comment]
Yes, adding a PHP QR generator will likely introduce a lot of code. That's why I proposed a hook, so it can be done in an add-on plugin (one of which I already have to enforce 2FA and remove soem methods my client doesn't need).

I imagine that such a hook could remain in place, even if a local generator is implemented later.

**Comment by iandunn** [comment]
#487 replaced the Google generator with a local one, so there's no longer an external URL to filter.

There are the existing `two_factor_totp_title` and the new `two_factor_totp_url` filters though, to customize the locally-generated code.
