### ISSUE TITLE
Adding and readying security keys no longer works

### ISSUE THREAD

**Issue by ishristov** [WordPress/two-factor#448]
Adding a new security key used to work on Brave on MacOS a few weeks/months ago, but now it doesn't - not on Brave, not on Chrome.

When I'm trying to add a new key, the loading spinner never goes away and the key is never read and added.

**Comment by ivanshcherbakov** [comment]
Hello! The same problem - when adding a secret key (Yubikey), the circle rotates endlessly and there is no addition. **Version plugin  0.7.1**,**WordPress version 6.0.1** .Windows 10 system (browsers: **Chrome**,**Yandex browser**,**Edge**). Yubikey is added to other sites without any problems. I will be very grateful to the developers for solving this problem."Two factor" this is the only one plugin that has support for adding a yubikey keys.

**Comment by kasparsd** [comment]
Could this be related to U2F API being removed from the Chrome engine as discussed in #423?

**Comment by ivanshcherbakov** [comment]
> Could this be related to U2F API being removed from the Chrome engine as discussed in #423?
[kasparsd](https://github.com/kasparsd),Thank you for the answer. So I will use the "WP-WebAuthn plugin"
