### ISSUE TITLE
TOTP codes failing

### ISSUE THREAD

**Issue by B-Interactive** [WordPress/two-factor#452]
For now, I've needed to disable the plugin on three separate sites, as it's suddenly failing to accept codes.

On one site, I temporarily renamed the plugin (so I could login), then re-activated it.  Then within my user profile, reset my OTP credentials, but it failed to accept my confirmation code still.

Unfortunately, I've not been able to locate any useful data in the error log.

**Comment by kasparsd** [comment]
Sorry to hear about your troubles!

This could happen if the server clock is out of sync. Not sure if there is a user friendly way to verify that.

Closing until we have more details on the setup and steps to replicate the issue.

**Comment by B-Interactive** [comment]
Well spotted @kasparsd.  I can confirm, running an NTP update on the server resolved the issue.
