### ISSUE TITLE
Encourage setting up a recovery factor

### ISSUE THREAD

**Issue by iandunn** [WordPress/two-factor#485]
Ideally users should setup two factors, one as a primary and one as a backup. e.g., WebAuthn as the primary and TOTP as the backup; or TOTP as the primary and Backup Codes as the backup.

Otherwise, they could get locked out of their account. On smaller sites an admin could reset them, but that's not practical on larger sites, or sites where the admin doesn't personally know the user.

Rough idea:

![Screen Shot 2022-10-20 at 9 39 20 AM](https://user-images.githubusercontent.com/484068/197007894-768533df-81ff-484c-89e7-bf49062155e7.png)

**Comment by kasparsd** [comment]
I really think this is a major step in ensuring that users configure their two-factors in a way that reduces their risk of being locked out of accounts. I'll work on a quick prototype for this.
