### ISSUE TITLE
New users bypassing 2FA

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/two-factor#492]
I created a new user account and I was able to bypass 2FA even though I have it set as mandatory on first login, I checked the user profile and see 'User has not logged in yet, 2FA status is unknown'. It doesn't even prompt for 2FA code.

Still working for existing users.

WP 6.0.2
Web server | nginx/1.19.10
PHP version | 7.4.23 (Supports 64bit values)
Chrome browser

I tried disabling all plugins. Also it's occurring on multiple sites that are WP 6.0+

**Comment by TimothyBJacobs** [comment]
Hi @LukaszJaro,

This repo is for the official Two-Factor feature plugin. You look to be experiencing an issue with [this plugin](https://wordpress.org/plugins/wp-2fa/). You can try creating a support topic in their forums.

**Comment by LukaszJaro** [comment]
YES!, sorry and thank you!
