### ISSUE TITLE
Register FIDO Key does not work

### ISSUE THREAD

**Issue by Bluematrix2** [WordPress/two-factor#498]
Hi all, 
I'm currently trying to register a YubiKey to multiple different WP pages. 
However, it always stuck at the register process and does not go forward. 

I tried chrome and egde, on WP 6.1.1 and PHP 7.4 and 8.1 all does have https on, no luck. 

Any idea what I could do? 
Thanks
Florian

**Comment by 11nu** [comment]
Hi @Bluematrix2!
I am not a developer of this project, but I think this is a known issue #423.
According to [a comment](https://github.com/WordPress/two-factor/issues/423#issuecomment-1301238061) on the issue, it will be resolved in 0.8.0 release, but until then I am using [WebAuthn Provider for Two Factor](https://wordpress.org/plugins/two-factor-provider-webauthn/) plugin as a work-around.

**Comment by Bluematrix2** [comment]
hi @11nu 
seams like it. Thanks for pointing me in the right direction. 
Hope 0.8.0 will come soon :)

**Comment by iandunn** [comment]
That's right, some additional info is in #488
