### ISSUE TITLE
PHP8 compatibility error 

### ISSUE THREAD

**Issue by adnaanqureshi** [WordPress/two-factor#499]
Error message: Uncaught Error: Call to undefined function create_function() in /home/newcast1/public_html/wp-content/plugins/two-factor-sms/includes/Twilio/Services/Twilio/Resource.php:93

**Comment by kasparsd** [comment]
Thanks for reporting the issue! Based on the error message it appears to be caused by the `two-factor-sms` plugin instead of the this Two Factor plugin. Can you please confirm?

**Comment by adnaanqureshi** [comment]
Yes - I was under the impression you maintained this add on? Perhaps not! Any idea who does?

**Comment by dd32** [comment]
The `two-factor-sms` plugins listed here: https://wordpress.org/plugins/two-factor-sms/ appears to have been last-updated 7 years ago, and suggests submitting PRs or issues on https://github.com/shield-9/two-factor-sms
