### ISSUE TITLE
Backup codes, all codes starting by a "0" are not works

### ISSUE THREAD

**Issue by sovetski** [WordPress/two-factor#500]
I am using the version 0.7.3 of the plugin.

When a backup code is created, if it starts with a zero, it not works.

You can try to generate a manual backup codes and try these ones:

09194093
01787213
07344118

They will not work, but all other possibilites seems ok like:

30444268
99254066

etc.

**Comment by dd32** [comment]
I've tested this, and I'm unable to verify it using the latest master from GitHub or the 0.7.3 version.

@sovetski Do you have any other two-factor related plugins installed?

Screen recording of it working:

https://user-images.githubusercontent.com/767313/204183144-af9e8f6b-426d-4940-b471-4c3d59a87a87.mov

**Comment by sovetski** [comment]
> I've tested this, and I'm unable to verify it using the latest master from GitHub or the 0.7.3 version.
> 
> @sovetski Do you have any other two-factor related plugins installed?
> 
> Screen recording of it working:
> 
>  Screen.Recording.2022-11-28.at.1.15.47.pm.mov

Thank you, it helped me! I checked my code, and I was added "intval()" filter to received $_POST values, and this function does not like any "0": https://www.php.net/manual/fr/function.intval.php

So if someone has the same problem one day, double-check your code! 👍
