### ISSUE TITLE
Question: How do I prevent the 2fa for work on staging sites?

### ISSUE THREAD

**Issue by planetahuevo** [WordPress/two-factor#505]
Hi, 
I am trying to have a mu plugin that disables the 2fa on the staging site. 

I know I need to use two_factor_providers or two_factor_enabled_providers_for_user to override the settings, but I have not found any examples so far (read most of the issues here and some of the forum posts too). 
I am struggling to make something that works. 
My code starts checking the environment: 
`if ( 'production' !== wp_get_environment_type() ) ` 
And then I want to add a filter 
`add_filter( 'two_factor_enabled_providers_for_user'...`
But I have no idea how to disable the whole thing. 
Any tips, docs, links or help that you could do it will be great. 

Thanks

**Comment by planetahuevo** [comment]
I end up modifying the current "force email 2fa" code and force the Dummy instead.
```
add_filter(
    'two_factor_enabled_providers_for_user',
    function( $providers ) {
        if ( class_exists( 'Two_Factor_Dummy' ) ) {
            $providers[] = 'Two_Factor_Dummy';
        }

        return $providers;
    },10,2);
```
Not the best solution but good enough for what I need. 
I was playing with 
`unset( $providers['Two_Factor_Email'] );`
But I was not sure where to put that, a function?, a filter? 
If someone can add here a code that works with the unset and remove all of them for all users, it would be great. 
in the meantime, I can live with the dummy questions. :)

**Comment by ramonfincken** [comment]
You are posting in WP Core. As far as I know there is no 2 factor in Core.

Therefore you are using a plugin right ? Please use the plugin support forums for that.

**Comment by planetahuevo** [comment]
I am posting on this repo: https://github.com/WordPress/two-factor
Which is related to this plugin: "Two-Factor plugin for WordPress. [View on WordPress.org →](https://wordpress.org/plugins/two-factor/)"
Which does not answer too much on the forum but also redirect to this github...

**Comment by planetahuevo** [comment]
No worries. :) 
I thought on posting there, but considering this is code, the lack of replies on the forum (0 issues resolved on the past 2 months) and that there are similar questions answered here in the past, about how to use the provided filters, I decided to ask here. I may be wrong as well. :)

**Comment by pkevan** [comment]
hi @planetahuevo, please post your question to the forum, since the issues here relate to issues with the code itself, and not with setup/usage etc.

**Comment by dd32** [comment]
To disable it for a user conditionally, you can filter on `two_factor_primary_provider_for_user` and return either the Dummy provider, or false.

Ideally, you shouldn't have the plugin enabled if you don't wish to have it activated though.
