### ISSUE TITLE
Simplify alternate authentication method link text

### ISSUE THREAD

**Issue by ironprogrammer** [WordPress/two-factor#516]
The alternate authentication method link text is prefixed with "Or, use your backup method:", regardless of whether this is the TOTP screen or the "backup method" screen that accepts single-use backup codes.

Consider simplifying these links to:
- On TOTP screen: "Or use a Backup Verification Code (Single Use)"
- On B/U Codes screen: "Or use a Time-Based One-Time Password (TOTP)"

**Comment by iandunn** [comment]
I like that idea 👍🏻

**Comment by dd32** [comment]
I personally like the WordPress.com login flow which doesn't have to use the "Or use X" wording, instead it uses "Continue with X"

Eg:
| Security Key, Switch to Auth app? | Auth App, Switch to Security Key? | Clicked "I can't access my phone" (Backup codes) |
| --- | --- | --- |
| <img width="465" alt="Screenshot 2023-02-14 at 1 42 37 pm" src="https://user-images.githubusercontent.com/767313/218633889-c5950f0f-d318-45ad-b3aa-be315c551364.png"> | <img width="432" alt="Screenshot 2023-02-14 at 1 42 51 pm" src="https://user-images.githubusercontent.com/767313/218633911-64ba1dc8-a14f-4fe5-9730-bc6e2bb998e7.png"> | <img width="436" alt="Screenshot 2023-02-14 at 1 43 02 pm" src="https://user-images.githubusercontent.com/767313/218633945-696a63dd-678a-439c-b4fb-06c7a7822afe.png"> |

Much clearer text, no need to clarify that things are one-time passwords, or use technical terms (Time-based one-time password)
