### ISSUE TITLE
Tests should run against WordPress stable and WordPress trunk, and supported PHP versions

### ISSUE THREAD

**Issue by dd32** [WordPress/two-factor#523]
Currently the unit tests only run on PHP 7.4 against the stable version of WordPress, with a PHP8 lint.

Ideally, they should run both on the latest Stable of WordPress, WordPress trunk, and ideally all PHP versions supported (or at least the lowest and highest).

**Comment by KZeni** [comment]
I would definitely like to second this. Version 0.8.0 was released with a bug that caused a site-wide fatal server error on PHP 7.2 (which this plugin says it supports per the current requirement being 5.6+.)

More details on this instance at: https://wordpress.org/support/topic/fatal-error-php-7-2-syntax-error-breaking-whole-site-3/
Related Issue: https://github.com/WordPress/two-factor/issues/548
Related PR: https://github.com/WordPress/two-factor/pull/547

Either have tests for all versions that it says this supports before release, or they might just need to increase the required PHP version (after releasing a hotfix for the current issue affecting PHP 7.2 users, if they do go that route.)

**Comment by iandunn** [comment]
I think it'd also be good to test on the minimum _WP_ version that's supported.
