### ISSUE TITLE
U2F doesn't work anymore

### ISSUE THREAD

**Issue by omicronn** [WordPress/two-factor#554]
### Describe the bug

During authentication the U2F key doesn't flash and nothing happend !

### Steps to Reproduce

Try to connect to wp-admin with login + pass
Wait for the key light 
Nothing happened

### Environment information

WP 6.2
PHP 8.0
Key Yubikey

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that you have tested with all plugins deactivated except Two-Factor.

Yes

**Comment by todeveni** [comment]
Duplicate of #553?

**Comment by omicronn** [comment]
Duplicate of 553 !
