### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by neppers3** [WordPress/two-factor#576]
Any language support for "frontend"-login and the email sent out would be great. Sign me up for norwegian translation. :-)

**Comment by dd32** [comment]
Hi @neppers3,

The plugin is fully translatable, and can be translated via translate.wordpress.org, it appears that Norwegian is at 98% completion: https://translate.wordpress.org/projects/wp-plugins/two-factor/

It does appear as if the Email provider does only email the user in the sites language however, and it does not respect the users locale selection (Although it should support the language selector on wp-login.php).

Could you clarify a little bit as to what you're looking for? If the above doesn't cover it.

Thanks!

**Comment by jeffpaul** [comment]
Closing as `stale`.
