### ISSUE TITLE
Implement Disable Provider method

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/two-factor#585]
Two_Factor_Core provides a [method](https://github.com/WordPress/two-factor/blob/master/class-two-factor-core.php#L1796) `enable_provider_for_user`.

To compliment this, a method should be added `disable_provider_for_user`, which takes similar arguments ( `$user_id`, `$provider` ) and also returns a boolean.

**Comment by dd32** [comment]
@adamwoodnz Can you update this with a two-factor specific request, rather than the wporg-two-factor requirements?

I think this is something like "There should be an API to compliment enable_provider_for_user() to disable a provider"?
