### ISSUE TITLE
Cannot register u2f key - failed to execute 'PostMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by wojciech-kochanski** [WordPress/two-factor#590]
### Describe the bug

Hello, 

I have a fresh installation of the plugin and I cannot register the u2f key.
I'm using WP v6.3.2., and Two-Factor v0.8.2

The console log shows the following:
![image](https://github.com/WordPress/two-factor/assets/148864326/8e4667f3-b0ca-48df-976a-06969456dd00)

Tested with all other plugins disabled, no difference.

### Steps to Reproduce

1. Have WP v6.3.2.
2. Install Two-Factor v0.8.2
3. Go to user settings and click button to register a new key
4. Button remains pressed forever (no response, message or whatever, just stuck, waiting circle is moving) and the console log is shown
5. no profit

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that you have tested with all plugins deactivated except Two-Factor.

Yes

**Comment by kasparsd** [comment]
Sorry for the confusion @wojciech-kochanski -- support for FIDO U2F has been removed [in most browsers](https://thenewstack.io/deprecation-from-u2f-api-to-webauthn/) in favour of WebAuthn. There is a WP plugin that adds support for WebAuthn to the two-factor plugin which should keep all the previously registered keys working https://wordpress.org/plugins/two-factor-provider-webauthn/

See #511 #423 and #232.
