### ISSUE TITLE
incompatibility with v6.4.1 of WordPress

### ISSUE THREAD

**Issue by nikitickets** [WordPress/two-factor#591]
### Describe the bug

Sites in my network are randomly not receiving the codes via email any longer. In the plugin repo on Wordpress, it notes Two Factor plugin is not yet compatible with 6.4.1 WP version. Will there be an update soon? Thank you!

### Steps to Reproduce

Try to log in.
The code will sometimes arrive, sometimes not.
On Wordpress, it notes the Two Factor plugin is not tested with 6.4.1 WP version yet.

### Environment information

WP 6.4.1 

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that you have tested with all plugins deactivated except Two-Factor.

No

**Comment by kasparsd** [comment]
This plugin relies on WP core methods for sending email so the delivery of these emails depends solely on that setup.

https://github.com/WordPress/two-factor/blob/88b503c0b3a8cede20a4dab24744917e49fbdb76/providers/class-two-factor-email.php#L243
