### ISSUE TITLE
Plugin hangs when the security plugin option is clicked

### ISSUE THREAD

**Issue by ralphbeckett** [WordPress/two-factor#596]
### Describe the bug

The security key option hangs when that option is selected to setup the key. I have a Yubi Key plugged into my computer.

### Steps to Reproduce

see the image. All I do is click "Register NewKey" and a little rotating icon appears and never goes away. I did push the button on the Yubi Key - no luck.

### Screenshots, screen recording, code snippet

![Screenshot 2024-03-13 at 09-36-32 Edit User Ralph Beckett ‹ Water For Humans — WordPress](https://github.com/WordPress/two-factor/assets/3208889/9b4a7401-6948-4897-9da9-e01c9f33b40d)

### Environment information

wordpress 6.4.3
The plugin works fine except this one feature. I have not closed down all the other plugins since I will simply not use the feature if I need to drop one of the other plugins.

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that you have tested with all plugins deactivated except Two-Factor.

No

**Comment by kasparsd** [comment]
@ralphbeckett This is most likely due to FIDO U2F support in browsers being removed in favour of webauthn, see #423 and #427.

I've personally had great success with using the https://github.com/sjinks/wp-two-factor-provider-webauthn which supports existing U2F key credentials.
