### ISSUE TITLE
Limit WP.org readme.txt tags to 5

### ISSUE THREAD

**Issue by kasparsd** [WordPress/two-factor#607]
### Is your enhancement related to a problem? Please describe.

The WP.org listing now displays the following warning to any contributor associated with this plugin "One or more tags were ignored: fido u2f, u2f, email, backup codes, 2fa, yubikey. Please limit your plugin to 5 tags."

Currently the plugin specifies the following tags: two factor, two step, authentication, login, totp, fido u2f, u2f, email, backup codes, 2fa, yubikey.

### Proposed Solution

Keep the following tags: 2fa, mfa, totp, authentication, security

### Please confirm that you have searched existing issues in this repository.

Yes

**Comment by jeffpaul** [comment]
> Keep the following tags: 2fa, mfa, totp, authentication, security

Seems like a good list to me.
