### ISSUE TITLE
Replace table tags with div tags to match Application Passwords styles

### ISSUE THREAD

**Issue by christofervas** [WordPress/two-factor#622]
### Is your enhancement related to a problem? Please describe.

The current design of the "Two-Factor Options" section uses HTML tables, which results in a design mismatch compared to the "Application Passwords" section, which utilizes div tags for its headings. This inconsistency is visually noticeable and affects the overall cohesiveness of the UI, as demonstrated in the attached screenshot where basic styles have been applied.

### Proposed Solution

To improve the visual consistency and maintain a uniform design language across the profile settings page, I recommend replacing the "Two-Factor Options" heading with div tags, aligning it with the styling approach used in the "Application Passwords" section.

### Designs

![Screenshot 2024-08-06 122511](https://github.com/user-attachments/assets/99b81db3-6972-4407-ba61-47b30a99626e)

### Please confirm that you have searched existing issues in this repository.

Yes

**Comment by dd32** [comment]
Hi @christofervas,

The image you've posted appears to show an interface that's not entirely core WordPress, are you using WordPress.com hosting by chance?

FWIW though, I do agree in changing this to the Application Passwords table format, as it suits that display type better than it does the existing table structure used by other profile fields on the page:

<img width="1568" alt="Screenshot 2024-08-19 at 2 59 31 PM" src="https://github.com/user-attachments/assets/6a282e3c-c6c6-4622-bc93-117cdeb3910b">

**Comment by christofervas** [comment]
Hey @dd32 thank you for considering this enchantment. Hope to see it in the next release.

This is not a WordPress.com hosting but we have applied some custom styles in the admin area.
