### ISSUE TITLE
Improve Discoverability of Plugin

### ISSUE THREAD

**Issue by PluginVulnerabilities** [WordPress/two-factor#631]
### Is your enhancement related to a problem? Please describe.

When searching the WordPress Plugin Directory for "2fa" the plugin doesn't show up.

### Proposed Solution

It would be best if the search functionality of the plugin directory was improved. But perhaps the term "2fa" could be mentioned in listing for the plugin so that it would be easier for users to find the plugin.

Also, on the plugin directory, the plugin is listed as being by "By Plugin Contributors," which makes the plugin seem somewhat sketchy. Other plugins from WordPress list the developer as [WordPress Contributors](https://wordpress.org/plugins/classic-editor/) or [The WordPress.org community](https://wordpress.org/plugins/health-check/). It doesn't appear there is currently any badge to confirm that a plugin is really coming from WordPress that could also be implemented to better show the plugin is from WordPress.

### Please confirm that you have searched existing issues in this repository.

Yes

**Comment by kasparsd** [comment]
Totally agree! 

This is somewhat related to #607 which reduced the amount of tags in readme.txt header to 5 and should now pick up `2fa` as being associated with this plugin:

https://github.com/WordPress/two-factor/blob/cfbfcd24b4287e2548aacc5c23fc6d820b7e13e6/readme.txt#L3

This hasn't gone to WP.org, though.

**Comment by jeffpaul** [comment]
Also relates to the short description, getting that tweaked to similarly include 2FA (and maybe even the plugin name) would help surface the plugin for that sort of search as well:

https://github.com/WordPress/two-factor/blob/71b49316370208aab76fde73e84dcdf34078e4cc/readme.txt#L9C1-L9C150

https://github.com/WordPress/two-factor/blob/71b49316370208aab76fde73e84dcdf34078e4cc/readme.txt#L1

https://github.com/WordPress/two-factor/blob/71b49316370208aab76fde73e84dcdf34078e4cc/two-factor.php#L11

**Comment by jeffpaul** [comment]
In terms of the author, that's listed here:

https://github.com/WordPress/two-factor/blob/71b49316370208aab76fde73e84dcdf34078e4cc/two-factor.php#L17

Perhaps best to put that as `WordPress.org Contributors`?

**Comment by jeffpaul** [comment]
Perhaps also some question as to whether, again for discoverability, if we also include `Multi-factor authentication (MFA)`? in the long description?
