### ISSUE TITLE
Cannot add U2F key for another user

### ISSUE THREAD

**Issue by dbrgn** [WordPress/two-factor#88]
I logged in as the admin user and tried to add a U2F YubiKey to another user (through the user management). When touching the YubiKey button, the message "Profile updated" appeared but the key was not added. I tried this 2 or 3 times, never worked.

I then logged in as that user directly and adding the key worked.

Can someone reproduce this? :)

**Comment by dbrgn** [comment]
(This happened using the version in the plugin directory.)

**Comment by kasparsd** [comment]
Should this be allowed?

This limitation is currently introduced by [this logic here](https://github.com/georgestephanis/two-factor/blob/b3e2eec7f4804ecc673e7ce9c644b9a6795c7158/providers/class.two-factor-fido-u2f-admin.php#L58).

**Comment by dbrgn** [comment]
> Should this be allowed?

I think so, yes. Admins should be able to pre-configure keys for other users before handing them out.

**Comment by kasparsd** [comment]
That is a good point @dbrgn! Let's fix this.
