### ISSUE TITLE
Pressing "Enter" instead of clicking the "Update Profile" button fails to enable the TOTP

### ISSUE THREAD

**Issue by kasparsd** [WordPress/two-factor#91]
Looks like the `personal_options_update` filter isn't triggered when using the Enter key after entering the value in `two-factor-totp-authcode` input field.

**Comment by georgestephanis** [comment]
Honestly, this needs a rewrite, probably moving more toward javascriptness.  The fact that there isn't a button to update it in easy reach means some folks will probably update it and not think to scroll all the way to the bottom.  Which kinda sucks.

We would probably gain significantly if @johnjamesjacoby's tabbed user profile page gets merged into core, so all the 2fa stuff could be bumped to a new tab.

**Comment by valendesigns** [comment]
@georgestephanis Could you link to the trac ticket?

**Comment by hummel124** [comment]
For me it's the other way round. I have to press enter to activate the TOTP.
When I use the "Update Profile" Button it is NOT activated!
Version is 0.1-dev-20170320

**Comment by kasparsd** [comment]
Closing this as duplicate of #556 which will be fixed with #643.
